"""
ARIA Meta-Controller: Trains a tiny MLP on labeled runtime features and
exports the weights as a self-contained C header (no TFLite/EON needed --
network is small enough for a hand-coded forward pass).

Usage:
    python3 train_meta_controller.py

Requires: pandas, numpy, scikit-learn (pip install pandas numpy scikit-learn)

Input : meta_controller_training_data.csv (from label_meta_controller_data_v3.py)
Output: meta_controller_weights.h
"""

import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample
from sklearn.metrics import confusion_matrix, classification_report

INPUT_CSV = "meta_controller_training_data.csv"
OUTPUT_HEADER = "meta_controller_weights.h"
HIDDEN_UNITS = 8
RANDOM_STATE = 42

df = pd.read_csv(INPUT_CSV)
X = df[["confidence_avg", "confidence_trend", "signal_delta", "latency_us"]].values
y = df["label"].values

print(f"Loaded {len(df)} rows. Label distribution: {df['label'].value_counts().to_dict()}")

# Oversample minority classes so small classes aren't ignored during training
dfs = []
max_count = df["label"].value_counts().max()
for lbl in sorted(df["label"].unique()):
    sub = df[df["label"] == lbl]
    sub_up = resample(sub, replace=True, n_samples=max_count, random_state=RANDOM_STATE)
    dfs.append(sub_up)
df_bal = pd.concat(dfs).sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)

X_bal = df_bal[["confidence_avg", "confidence_trend", "signal_delta", "latency_us"]].values
y_bal = df_bal["label"].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_bal)

clf = MLPClassifier(
    hidden_layer_sizes=(HIDDEN_UNITS,),
    activation="relu",
    max_iter=3000,
    random_state=RANDOM_STATE,
    alpha=1e-3,
)
clf.fit(X_scaled, y_bal)

# Evaluate on original (non-oversampled) data for an honest read
X_orig_scaled = scaler.transform(X)
pred = clf.predict(X_orig_scaled)
print("\nTraining-set (original, non-oversampled) performance:")
print(confusion_matrix(y, pred))
print(classification_report(y, pred, target_names=["Fast", "Balanced", "Accurate"]))


def fmt_array(name, arr):
    if arr.ndim == 1:
        vals = ", ".join(f"{v:.8f}f" for v in arr)
        return f"static const float {name}[{arr.shape[0]}] = {{ {vals} }};"
    else:
        rows = ", ".join("{" + ", ".join(f"{v:.8f}f" for v in row) + "}" for row in arr)
        return f"static const float {name}[{arr.shape[0]}][{arr.shape[1]}] = {{ {rows} }};"


W1, b1 = clf.coefs_[0], clf.intercepts_[0]
W2, b2 = clf.coefs_[1], clf.intercepts_[1]
mean, scale = scaler.mean_, scaler.scale_

header = f"""/* Auto-generated by train_meta_controller.py -- do not hand-edit.
 * Trained on {len(df)} labeled runtime feature rows.
 * Architecture: 4 inputs -> {HIDDEN_UNITS} hidden (ReLU) -> 3 outputs (argmax = variant)
 * Labels: 0 = VARIANT_FAST, 1 = VARIANT_BALANCED, 2 = VARIANT_ACCURATE
 */
#ifndef META_CONTROLLER_WEIGHTS_H
#define META_CONTROLLER_WEIGHTS_H

{fmt_array("META_SCALER_MEAN", mean)}
{fmt_array("META_SCALER_SCALE", scale)}

{fmt_array("META_W1", W1)}
{fmt_array("META_B1", b1)}
{fmt_array("META_W2", W2)}
{fmt_array("META_B2", b2)}

static inline int meta_controller_predict(float confidence_avg, float confidence_trend,
                                           float signal_delta, float latency_us)
{{
    float x[4] = {{ confidence_avg, confidence_trend, signal_delta, latency_us }};
    float xs[4];
    for (int i = 0; i < 4; i++) {{
        xs[i] = (x[i] - META_SCALER_MEAN[i]) / META_SCALER_SCALE[i];
    }}

    float h[{HIDDEN_UNITS}];
    for (int j = 0; j < {HIDDEN_UNITS}; j++) {{
        float sum = META_B1[j];
        for (int i = 0; i < 4; i++) {{
            sum += xs[i] * META_W1[i][j];
        }}
        h[j] = (sum > 0.0f) ? sum : 0.0f;
    }}

    float out[3];
    for (int k = 0; k < 3; k++) {{
        float sum = META_B2[k];
        for (int j = 0; j < {HIDDEN_UNITS}; j++) {{
            sum += h[j] * META_W2[j][k];
        }}
        out[k] = sum;
    }}

    int best = 0;
    for (int k = 1; k < 3; k++) {{
        if (out[k] > out[best]) best = k;
    }}
    return best;
}}

#endif /* META_CONTROLLER_WEIGHTS_H */
"""

with open(OUTPUT_HEADER, "w") as f:
    f.write(header)

print(f"\nWrote {OUTPUT_HEADER}")
