/* Auto-generated by train_meta_controller.py (v5) -- do not hand-edit.
 * Trained on 354 labeled runtime feature rows (file-identity ground truth),
 * fit on the FULL dataset (cross-validation was used only for model selection).
 * Architecture: 4 inputs -> 16 hidden (ReLU) -> 3 outputs (argmax = variant)
 * Labels: 0 = VARIANT_FAST, 1 = VARIANT_BALANCED, 2 = VARIANT_ACCURATE
 * Features: confidence_avg, confidence_trend, signal_delta, signal_rms
 *           (latency_us intentionally excluded -- near-zero variance, dominated old model)
 * Full-data train acc: 0.791
 * See cross-validation sweep in training script output for generalization estimate.
 */
#ifndef META_CONTROLLER_WEIGHTS_H
#define META_CONTROLLER_WEIGHTS_H

#define META_HIDDEN_UNITS (16)

static const float META_SCALER_MEAN[4] = { 0.60521863f, 0.00602489f, 0.00865315f, 0.69917620f };
static const float META_SCALER_SCALE[4] = { 0.36741456f, 0.27871455f, 0.29355310f, 0.60512939f };

static const float META_W1[4][META_HIDDEN_UNITS] = { { -0.83204496f, 1.11554567f, 0.68405661f, 0.03556659f, -1.01852186f, -0.75130823f, -0.87986573f, 0.07964130f, -0.42630349f, 0.04200038f, -0.23763108f, 1.14993115f, 0.01725186f, -0.23863778f, -1.09290205f, -0.25788033f }, { -0.46267337f, -0.09112333f, -0.18784919f, -0.14507779f, 0.10899257f, -0.32624622f, -0.16096507f, -0.25259747f, -0.13484505f, 0.54570106f, -0.01495723f, 0.06438933f, 0.67937174f, -0.84096359f, 0.09985131f, -0.76406419f }, { -0.44433783f, 0.27878711f, 0.65066935f, 0.60692055f, -0.65522406f, -0.05511572f, 0.30926618f, -0.57821910f, -0.26953376f, 0.09538460f, -1.18786113f, 0.40292451f, -0.78810527f, 0.24370239f, 0.16538473f, -0.12629363f }, { -0.18282010f, -0.78942600f, 0.79443488f, 0.58412544f, 0.86325355f, 0.09504784f, -0.09836607f, 0.88224563f, -0.55942852f, -0.65727446f, 0.00453144f, -0.71925334f, 0.04421306f, -0.21228559f, -0.05428082f, -0.10265662f } };
static const float META_B1[META_HIDDEN_UNITS] = { -0.19114836f, 0.65524073f, -0.15110799f, 0.62422957f, -0.49096391f, 0.61412359f, 0.56249712f, -0.57339789f, -0.89190987f, 0.40624188f, 0.15232178f, 0.78831447f, 0.05174773f, -0.56796197f, 0.36381795f, -0.50427631f };
static const float META_W2[META_HIDDEN_UNITS][3] = { { 0.81056217f, 0.21238399f, -0.78684009f }, { -1.21894749f, 0.34184935f, -0.05987768f }, { -0.08062774f, 0.59376375f, 0.48757222f }, { -0.30984532f, -0.34340865f, 0.64251596f }, { -0.88315189f, -0.28955814f, 1.24876136f }, { 0.25203219f, -0.46982894f, -0.07284004f }, { -0.28678721f, -0.88739958f, -0.60512869f }, { -0.15232201f, 0.68317646f, -0.76767732f }, { 0.77766676f, -1.02391982f, -0.11131879f }, { 0.31150029f, 0.57652259f, -0.99339277f }, { -0.09958906f, -0.67462650f, 0.42546937f }, { -0.26875901f, 0.51898787f, 0.77523226f }, { -0.02192354f, -0.21860723f, 1.08006322f }, { -0.17589564f, 0.46174039f, 0.59238018f }, { 0.17553230f, -1.28104332f, -0.20025799f }, { -0.26490456f, 0.58441590f, 0.47074709f } };
static const float META_B2[3] = { -0.79653752f, 0.26542379f, -0.02331457f };

static inline int meta_controller_predict(float confidence_avg, float confidence_trend,
                                           float signal_delta, float signal_rms)
{
    float x[4] = { confidence_avg, confidence_trend, signal_delta, signal_rms };
    float xs[4];
    for (int i = 0; i < 4; i++) {
        xs[i] = (x[i] - META_SCALER_MEAN[i]) / META_SCALER_SCALE[i];
    }

    float h[META_HIDDEN_UNITS];
    for (int j = 0; j < META_HIDDEN_UNITS; j++) {
        float sum = META_B1[j];
        for (int i = 0; i < 4; i++) {
            sum += xs[i] * META_W1[i][j];
        }
        h[j] = (sum > 0.0f) ? sum : 0.0f;
    }

    float out[3];
    for (int k = 0; k < 3; k++) {
        float sum = META_B2[k];
        for (int j = 0; j < META_HIDDEN_UNITS; j++) {
            sum += h[j] * META_W2[j][k];
        }
        out[k] = sum;
    }

    int best = 0;
    for (int k = 1; k < 3; k++) {
        if (out[k] > out[best]) best = k;
    }
    return best;
}

#endif /* META_CONTROLLER_WEIGHTS_H */
