/* Auto-generated by train_meta_controller.py -- do not hand-edit.
 * Trained on 100 labeled runtime feature rows.
 * Architecture: 4 inputs -> 8 hidden (ReLU) -> 3 outputs (argmax = variant)
 * Labels: 0 = VARIANT_FAST, 1 = VARIANT_BALANCED, 2 = VARIANT_ACCURATE
 */
#ifndef META_CONTROLLER_WEIGHTS_H
#define META_CONTROLLER_WEIGHTS_H

static const float META_SCALER_MEAN[4] = { 0.76723885f, 0.00348445f, -0.00261387f, 185.96713615f };
static const float META_SCALER_SCALE[4] = { 0.13839014f, 0.14822222f, 0.06058851f, 0.17828016f };

static const float META_W1[4][8] = { {-0.13969729f, 1.13900378f, -0.19508246f, -0.44513924f, -0.80526498f, -1.27052965f, -2.10682992f, 1.56309543f}, {0.04369014f, -0.15218667f, -0.57929540f, 0.52351610f, 1.63951058f, 0.49665232f, -1.25815536f, -0.85856072f}, {-0.10423188f, -0.72698957f, 2.86562587f, -3.26326583f, -0.17335743f, -2.59524715f, -1.12390459f, 0.00068695f}, {-0.86378255f, 0.85676995f, -0.30098867f, -0.05465780f, 0.76355446f, -0.29426007f, 0.80131508f, -1.21730471f} };
static const float META_B1[8] = { -0.36149837f, 1.10058132f, -0.07393351f, 0.41666454f, 0.37255433f, -1.11792819f, 1.09379921f, -0.70337499f };
static const float META_W2[8][3] = { {-0.61488798f, 0.71620353f, -1.24133456f}, {1.24864375f, -0.71394955f, -0.04328539f}, {-1.53385898f, -1.19463948f, 1.64982452f}, {-2.65087033f, 0.38565911f, 1.44653808f}, {-1.47402852f, 1.44377250f, -0.03784352f}, {0.40454355f, -2.48537095f, 1.52470880f}, {-2.60962597f, 0.56990259f, -0.19087809f}, {-2.77400301f, 2.09258975f, -0.04537216f} };
static const float META_B2[3] = { 0.27532434f, 0.06970494f, -0.93640548f };

static inline int meta_controller_predict(float confidence_avg, float confidence_trend,
                                           float signal_delta, float latency_us)
{
    float x[4] = { confidence_avg, confidence_trend, signal_delta, latency_us };
    float xs[4];
    for (int i = 0; i < 4; i++) {
        xs[i] = (x[i] - META_SCALER_MEAN[i]) / META_SCALER_SCALE[i];
    }

    float h[8];
    for (int j = 0; j < 8; j++) {
        float sum = META_B1[j];
        for (int i = 0; i < 4; i++) {
            sum += xs[i] * META_W1[i][j];
        }
        h[j] = (sum > 0.0f) ? sum : 0.0f;
    }

    float out[3];
    for (int k = 0; k < 3; k++) {
        float sum = META_B2[k];
        for (int j = 0; j < 8; j++) {
            sum += h[j] * META_W2[j][k];
        }
        out[k] = sum;
    }

    int best = 0;
    for (int k = 1; k < 3; k++) {
        if (out[k] > out[best]) best = k;
    }
    return best;
}

#endif /* META_CONTROLLER_WEIGHTS_H */
